language: node_js
node_js: lts/*
os:
  - linux
env:
  - NODE_ENV=test
services:
  - redis-server
install:
  - npm install
jobs:
  include:
    - stage: 'Deploy'
      script: ./scripts/build.sh
      deploy:
        provider: heroku
        api_key:
          secure: Q/y6+3Nq5yc8m3yPZm7FBeo9EKSauzccx0u9ky5cTHcdi90vgJKyWb0bn7r+8hgKgcFpvmLfSbE3Jjc95m35Cjn+FutKiyToZCEfRUwIXjEPbEL7Q08P0RMn89XfRx1gP0YHJtkpRjKIr/7l1KvYyzh8Fpyot1UkG42N+9ILBRlOksoexYsrNOo4n1VYkBE6w6D3pQYiSFZsz0EG2y7aizR4m64U3mc9qI+iKZ5yQsXFofEAvDLZodRm83lf5lqQC6C/rx/IuavsR5JZYAXGexGjUzqL4Rv2K8+29OSPOz3/      KIYVcHX4O77MzrphMSngXvsAgJkvQk9sOCY6EXx7lFy2vbvm2Vq4q60a3nLWKxPM7Hs2Hc6EkZTlLZ9ao3BNRCQcMPOVxJJI2HaI95wq5G5pfda20tA0RCBaTdr1vmPpBhk2JPnSfz8ZG+32RsAJtjk2+wUlYgYVXBud8+E+BpPXyNhCuVVeUnEJW2zOEFXX9l+VxDVzz4z/9I85qbfVDBjkAVZ9UNoPEvHQLj2KnY57zV6gEBDGuGUOYT9dDCLDLUmQDoP+yzKQmhIS    +PuKz2u3WpRFhUZtjC1zwYGheBUHJyAqtbdv/ZN9wK9gHLt2P8W6PIL9cRTw3q2nCNkEUn5X83Ez1A1Ol4fp6vMpRaeJBp5l0r5VkGUnH5G1Ct4=
        app: sukhiboi-blog
        run: restart
        skip_cleanup: true
