language: node_js
node_js: lts/*
os:
- linux
services:
- redis-server
install:
- npm install
jobs:
  include:
  - stage: Deploy
    script: "./scripts/build.sh"
    # deploy:
    #   provider: heroku
    #   api_key:
    #     secure: jdUo2juCWQu3sRtuzCSt1Rnr/Fq49xwv8Xw/g2HGV7n+JwZIHTWdz1RFAfGWTTF086Bc1X/S4Gu0Mz1iKPWP7OdJrGaBZOY9jGXUF6HlIlJhwLhZpEWWKQ4P3hX84z+VudcH55agwDhvfCaiswPLiUKxGt3QAL8UqJSrjVJpL/+oiusAlOnPqb/8CwpZ7sSNHiLnpe+z9A2kZbwJKdkzzAMKGPp3BwMuPgc4SxuFvNVVTKCNl/aQcIfJBqV17JAXUYzd5keaCaK5ruRDTl+BQgB31q7S/92CPqCbebFeW5U6OdRKhNT6/zO7JOeXwnW0mbuuaNEPWKXHf9Ftq5SMYa2edSIbBqYB9gt56Wqn8pQoOGaPpkoTETVQ9lMVb0LF+AXcbHy1/fmARhlWhFGBsWZiTq0xxaGgEEJ1fiDctEw2FZEo0+4D5jYZUZpUYWTCFu2TWjNHbs1G9D0nlIbmBDWWR3DSEb0Vsen4QJsh/riDBl32i76i6DiLdRkggjLfoO7x7x7JaDBl8Npr+L9s3a6RqLwupphD5uAcKh1c9InasQ50VFHcxPr+dXoEXGYtqs0b1ANpfBQG2lRqpN5ZFmzbpYWmRRmohNS8eUyFj07Raz6vDf1J1EgFxqyLcebq8ye3rhIphPuhvugDVL3Dco9Bo+op5zMvui31kN4z5JI=
    #   app: sukhiboi-blog
    #   run: restart
